// empty object in which to store everything
const tattApp = {};

// initialze an array to contain all "possible" tattoos
tattApp.allTattoos = [
 {
        name: "arrow",
        type: ["basic", "hippie", "minimalist"],
        meaning: ["no","icdMeaning","yes","it only flies forewards toward its goal. Anyone that stands in your way gets hit lmao"],
        size: ["small"],
        style: ["trendy", "traditional"],
        colour: "black",
        cost: ["$"],
        artist: ["Miniminiminiatures"],
        artistInsta:"https://www.instagram.com/minimini.studio/",
        artistImage: "/assets/minimini.jpg",
    },
    {
        name: "chain link fence with a hole in it",
        style: ["punk", "metal"],
        meaning: ["no","icdMeaning","yes", "you have broken through obstacles in your life. Note: this assumes that you have broken through obstacles in your life"],
        size: ["medium"],
        style: ["trendy"],
        colour: "black",
        cost: ["$$"],
        artist: ["Rat666Tat"],
        artistInsta: "PLACEHOLDER",
        artistImage: "/assets/PLACEHOLDER.jpg"
    },
    {
        name: "skull",
        style: ["punk", "metal"],
        meaning: ["no","icdMeaning","yes", "it is a reminder of the impermenance of life / memento mori if you wanna be Latin about it"],
        size: ["small", "medium", "large"],
        style: ["traditional"],
        colour: "black",
        cost: ["$", "$$", "$$$"],
        artist: ["c00pc00ptatt00s"],
        artistInsta: ""
    },
    // {
    //     name:,
    //     style:[],
    //     meaning:["no", "idcMeaning", "yes", ],
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    //     artistInsta: "",
    // },
    // {
    //     name:,
    //     style:[],
    //     meaning:[],
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    //  {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    //{
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // }
]
