// empty object in which to store everything
const tattApp = {};

// initialze an array to contain all "possible" tattoos
tattApp.allTattoos = [
 {
        name: "an arrow",
        type: ["basic", "hippie", "minimalist"],
        meaning: ["no","idcMeaning","yes","it only flies forewards toward its goal. Anyone that stands in your way gets hit lmao."],
        size: ["small"],
        style: ["trendy", "traditional", "idcStyle"],
        colour: ["black","idcColour"],
        cost: ["$"],
        artist: "Miniminiminiatures",
        artistInsta:"https://www.instagram.com/minimini.studio/",
        artistImage: "assets/minimini.png",
    },
    {
        name: "a chain link fence with a hole in it",
        type: ["punk"],
        meaning: ["no","idcMeaning","yes", "you have broken through obstacles in your life, assuming you have broken through obstacles in your life."],
        size: ["medium"],
        style: ["trendy", "idcStyle"],
        colour: ["black","idcColour"],
        cost: ["$$"],
        artist: "Rat666Tat",
        artistInsta: "https://www.instagram.com/rat666tat/",
        artistImage: "assets/rat666tat.png",
    },
    {
        name: "a wonky skull",
        type: ["alt"],
        meaning: ["no","idcMeaning","yes", "it is a reminder of the impermenance of life / memento mori if you really wanna be Latin about it."],
        size: ["small", "medium"],
        style: ["trendy", "idcStyle"],
        colour: ["black", "idcColour"],
        cost: ["$", "$$"],
        artist: "c00pc00ptatt00s",
        artistInsta: "https://www.instagram.com/c00pc00ptatt00s/",
        artistImage: "assets/coop.png",
    },
    {
        name:"a dinosaur skull",
        type:["punk", "metal"],
        meaning:["no", "idcMeaning"],
        size: ["medium","large"],
        style: ["traditional", "idcStyle"],
        colour: ["black", "idcColour"],
        cost: ["$", "$$"],
        artist: "E.K. Chan",
        artistInsta: "https://www.instagram.com/ek.tattoos/",
        artistImage: "assets/ekchan.jpg",
    },
    {
        name:"a lady doing yoga",
        type:["alt", "minimalist"],
        meaning: ["no", "idcMeaning"],
        size:["small", "medium"],
        style:["trendy"],
        colour:["no", "yes", "idcColour"],
        cost:["$"],
        artist:"mellowpokes",
        artistInsta:"https://www.instagram.com/mellowpokes/",
        artistImage:"assets/mellowpokes.png",
    },
    {
        name: "your VERY FAVORITE animal",
        type: ["punky", "metal", "gym"],
        meaning: ["no", "idcMeaning", "yes", "it is your patronus and it will be with you always :')"],
        size: ["small", "medium", "large"],
        style: ["traditional"],
        colour: ["no", "yes", "idcColour"],
        cost: ["$$", "$$$"],
        artist: "karyanntattoos",
        artistInsta: "https://www.instagram.com/karyanntattoos/",
        artistImage: "assets/karyann.png",
    },
    {
        name: "a sweet sweet cherub",
        type: ["punky", "gym"],
        meaning: ["no", "idcMeaning", "yes", "it'd be a visual representation of your shoulder angel reminding you to be nice."],
        size: ["small", "medium", "large"],
        style: ["traditional"],
        colour: ["no", "yes", "idcColour"],
        cost: ["$$", "$$$"],
        artist: "karyanntattoos",
        artistInsta: "https://www.instagram.com/karyanntattoos/",
        artistImage: "assets/karyann.png",
    },
    {
        name: "tattoo of \"family first\" in script (probably accross your chest)",
        type: ["gym"],
        meaning: ["no","idcMeaning", "yes", "because there is nothing more important than showing your family that you care abotu them thiiiis much"],
        size: ["small", "medium", "large"],
        style: ["traditional"],
        colour: ["no", "yes", "idcColour"],
        cost: ["$$", "$$$"],
        artist: "karyanntattoos",
        artistInsta: "https://www.instagram.com/karyanntattoos/",
        artistImage: "assets/karyann.png",
    },
    {
        name: "line down the side of your entire body",
        type: ["minimalist"],
        meaning: ["idcMeaning", "yes", "maybe you feel divided a lot of the time."],
        size: ["large"],
        style: ["trendy"],
        colour: ["no", "yes", "idcColour"],
        cost: ["$"],
        artist: "miniminiminiatures",
        artistInsta: "https://www.instagram.com/minimini.studio/",
        artistImage: "assets/minimini.png",
    },
    {
        name: "tattoo of your zodiac sign",
        type: ["basic", "hippie", "minimalist"],
        meaning: ["idcMeaning", "yes", "honestly astrology is really hot right now and sometimes you forget what yours is and it's embarassing."],
        size: ["small"],
        style: ["trendy", "traditional"],
        colour: ["no", "yes", "idcColour"],
        cost: ["$"],
        artist: "miniminiminiatures",
        artistInsta: "https://www.instagram.com/mellowpokes/",
        artistImage: "assets/mellowpokes.png",
    },
    {
        name: "tattoo of your favourite Beatles lyrics",
        type: ["hippie", "basic"],
        meaning: ["idcMeaning", "yes", "you are really able to look past the people themselves and just listen to the music."],
        size: ["small", "medium"],
        style: ["trendy", "traditional"],
        colour: ["no", "yes", "idcColour"],
        cost: ["$", "$$"],
        artist: "rattattooing",
        artistInsta: "https://www.instagram.com/rattattooing/",
        artistImage: "assets/rattattooing.png",
    },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // }
]
