// empty object in which to store everything
const tattApp = {};

// initialze an array to contain all "possible" tattoos
tattApp.allTattoos = [
 {
        name: "arrow",
        type: ["basic", "hippie", "minimalist"],
        meaning: ["no","idcMeaning","yes","it only flies forewards toward its goal. Anyone that stands in your way gets hit lmao"],
        size: ["small"],
        style: ["trendy", "traditional", "idcStyle"],
        colour: ["black","idcColour"],
        cost: ["$"],
        artist: ["Miniminiminiatures"],
        artistInsta:"https://www.instagram.com/minimini.studio/",
        artistImage: "../assets/minimini.jpg",
    },
    {
        name: "chain link fence with a hole in it",
        type: ["punk", "metal"],
        meaning: ["no","idcMeaning","yes", "you have broken through obstacles in your life. Note: this assumes that you have broken through obstacles in your life"],
        size: ["medium"],
        style: ["trendy", "idcStyle"],
        colour: ["black","idcColour"],
        cost: ["$$"],
        artist: ["Rat666Tat"],
        artistInsta: "https://www.instagram.com/rat666tat/",
        artistImage: "../assets/PLACEHOLDER.jpg",
    },
    {
        name: "skull",
        type: ["punk", "metal"],
        meaning: ["no","idcMeaning","yes", "it is a reminder of the impermenance of life / memento mori if you wanna be Latin about it"],
        size: ["small", "medium", "large"],
        style: ["traditional", "idcStyle"],
        colour: ["black", "idcColour"],
        cost: ["$", "$$", "$$$"],
        artist: ["c00pc00ptatt00s"],
        artistInsta: "https://www.instagram.com/c00pc00ptatt00s/",
        artistImage: "",
    },
    {
        name:"dinosaur skull",
        type:["punk", "metal"],
        meaning:["no", "idcMeaning"],
        size: ["medium","large"],
        style: ["traditional", "idcStyle"],
        colour: ["black", "idcColour"],
        cost: ["$", "$$"],
        artist: ["E.K. Chan"],
        artistInsta: "https://www.instagram.com/ek.tattoos/",
        artistImage: "../assets/ekchan.jpg",
    },
    // {
    //     name:,
    //     style:[],
    //     meaning:[],
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    //  {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    //{
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // }
]
