// empty object in which to store everything
const tattApp = {};

// initialize an object to contain all "possible" tattoos
tattApp.allTattoos = {
    tatt1: {
        name: "arrow",
        type: ["basic", "hippie", "minimalist"],
        meaning: ["yes", "it only flies forewards toward its goal. Anyone that stands in your way gets hit"],
        size: ["small"],
        style: ["trendy", "traditional"],
        colour: "black",
        cost: ["$"],
        artist: ["Miniminiminiatures"],
    },
    tatt2: {
        name: "chain link fence with a hole in it",
        style: ["punk", "metal"],
        meaning: ["yes", "you have broken through obstacles in your life. Note: this assumes that you have broken through obstacles in your life"],
        size: ["medium"],
        style: ["trendy"],
        colour: "no",
        cost: ["$$"],
        artist: ["Rat666Tat"],
    },
    tatt3: {
        name: "skull",
        style: ["punk", "metal"],
        meaning: ["yes", "it is a reminder of the impermenance of life / memento mori if you wanna sound Latin about it"],
        size: ["small", "medium", "large"],
        style: ["traditional"],
        colour: "black",
        cost: ["$", "$$", "$$$"],
        artist: ["c00pc00ptatt00s"],
    },
    //   tatt4: {
    //     name:,
    //     style:[],
    //     meaning:[],
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    //   tatt5: {
    //     name:,
    //     style:[],
    //     meaning:[],
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt6: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt7: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt8: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt9: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt10: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt11: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt12: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt13: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt14: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt15: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt16: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt17: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt18: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt19: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
    // tatt20: {
    //     name:,
    //     style:,
    //     meaning:,
    //     size:,
    //     style:,
    //     colour:,
    //     cost:,
    //     artist:,
    // },
};
